# Generated by Django 6.0.4 on 2026-04-16 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="动作")),
                (
                    "target_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="目标类型"
                    ),
                ),
                (
                    "target_id",
                    models.CharField(blank=True, max_length=64, verbose_name="目标ID"),
                ),
                (
                    "message",
                    models.CharField(blank=True, max_length=255, verbose_name="说明"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "path",
                    models.CharField(blank=True, max_length=255, verbose_name="路径"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作审计",
                "verbose_name_plural": "操作审计",
                "ordering": ["-created_at"],
            },
        ),
    ]
