# Generated by Django 6.0.4 on 2026-06-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operating_hours_text",
                    models.CharField(
                        blank=True,
                        default="10:00-21:00",
                        max_length=100,
                        verbose_name="园区营业时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "站点配置",
                "verbose_name_plural": "站点配置",
            },
        ),
    ]
