# Generated by Django 6.0.4 on 2026-04-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="项目名称"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("thrill", "刺激类"),
                            ("family", "亲子类"),
                            ("view", "观光类"),
                        ],
                        default="family",
                        max_length=20,
                        verbose_name="项目类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("maintenance", "维护"),
                            ("closed", "关停"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="运行状态",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=20, verbose_name="最大承载量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "游乐项目",
                "verbose_name_plural": "游乐项目",
                "ordering": ["name"],
            },
        ),
    ]
