# Generated by Django 6.0.4 on 2026-04-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="daily_warn_threshold",
            field=models.PositiveIntegerField(
                default=300, verbose_name="日客流预警阈值"
            ),
        ),
    ]
