# Generated by Django 6.0.4 on 2026-04-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_daily_warn_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entrance", "入口区"),
                    ("family", "亲子区"),
                    ("thrill", "刺激区"),
                    ("view", "观光区"),
                    ("rest", "休闲区"),
                    ("catering", "餐饮配套区"),
                ],
                max_length=20,
                null=True,
                verbose_name="所属园区区域",
            ),
        ),
    ]
