# Generated by Django 5.1.4 on 2026-04-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="project_covers/",
                verbose_name="封面图",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="地图纬度",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="地图经度",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="项目简介（游客端展示）"),
        ),
    ]
