# Generated by Django 6.0.4 on 2026-06-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_cover_image_project_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cycle_minutes",
            field=models.PositiveIntegerField(
                default=5, verbose_name="单轮游玩时长(分钟)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="operating_hours_text",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="运营时间说明"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="queue_count",
            field=models.PositiveIntegerField(default=0, verbose_name="当前排队人数"),
        ),
    ]
