# Generated by Django 6.0.4 on 2026-06-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0005_project_cycle_minutes_project_operating_hours_text_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("normal", "正常"),
                    ("maintenance", "维护"),
                    ("closed", "关闭"),
                ],
                default="normal",
                max_length=20,
                verbose_name="运行状态",
            ),
        ),
    ]
