# Generated by Django 6.0.4 on 2026-04-16 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("play_time", models.DateTimeField(verbose_name="游玩时间")),
                (
                    "queue_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="排队时长(分钟)"
                    ),
                ),
                (
                    "repeat_count",
                    models.PositiveIntegerField(default=0, verbose_name="重复游玩次数"),
                ),
                (
                    "status_snapshot",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("maintenance", "维护"),
                            ("closed", "关停"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="设备状态快照",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="录入时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="录入人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="projects.project",
                        verbose_name="游乐项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "游玩记录",
                "verbose_name_plural": "游玩记录",
                "ordering": ["-play_time", "-created_at"],
            },
        ),
    ]
