# Generated by Django 6.0.4 on 2026-06-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playrecord",
            name="status_snapshot",
            field=models.CharField(
                choices=[
                    ("normal", "正常"),
                    ("maintenance", "维护"),
                    ("closed", "关闭"),
                ],
                default="normal",
                max_length=20,
                verbose_name="设备状态快照",
            ),
        ),
    ]
