# Generated by Django 6.0.4 on 2026-06-01 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="手机号"
            ),
        ),
        migrations.AlterField(
            model_name="visitorprofile",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="昵称"
            ),
        ),
        migrations.AddConstraint(
            model_name="visitorprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("nickname__isnull", False),
                    models.Q(("nickname", ""), _negated=True),
                ),
                fields=("nickname",),
                name="uniq_profile_nickname_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="visitorprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("phone__isnull", False), models.Q(("phone", ""), _negated=True)
                ),
                fields=("phone",),
                name="uniq_profile_phone_not_blank",
            ),
        ),
    ]
