# Generated by Django 5.1.4 on 2026-04-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitor", "0001_visitor_favorite_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorfeedback",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
        ),
        migrations.AddField(
            model_name="visitorfeedback",
            name="status",
            field=models.CharField(
                choices=[("pending", "待处理"), ("resolved", "已处理")],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="处理状态",
            ),
        ),
    ]
