# Generated by Django 6.0.4 on 2026-06-01 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0005_project_cycle_minutes_project_operating_hours_text_and_more",
        ),
        ("visitor", "0002_feedback_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraryPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="方案名称")),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("family", "亲子家庭"),
                            ("adult", "成人游客"),
                            ("teen", "青少年"),
                        ],
                        default="family",
                        max_length=20,
                        verbose_name="适用人群",
                    ),
                ),
                (
                    "preference_tag",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="偏好标签"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="方案说明"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "行程规划模板",
                "verbose_name_plural": "行程规划模板",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VisitorFeedbackMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("visitor", "游客"), ("admin", "管理员")],
                        max_length=20,
                        verbose_name="发送方",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "read_by_visitor",
                    models.BooleanField(default=False, verbose_name="游客已读"),
                ),
                (
                    "read_by_admin",
                    models.BooleanField(default=False, verbose_name="管理员已读"),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="visitor.visitorfeedback",
                        verbose_name="反馈会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "反馈会话消息",
                "verbose_name_plural": "反馈会话消息",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ItineraryPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField(default=1, verbose_name="顺序")),
                (
                    "tip",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="提示"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="visitor.itineraryplan",
                        verbose_name="规划方案",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "行程规划项目",
                "verbose_name_plural": "行程规划项目",
                "ordering": ["seq", "id"],
                "unique_together": {("plan", "seq")},
            },
        ),
    ]
