# Generated by Django 6.0.4 on 2026-06-06 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("projects", "0006_alter_project_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="设施名称")),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("catering", "餐饮"),
                            ("retail", "文创零售"),
                            ("rest", "休闲服务"),
                        ],
                        default="rest",
                        max_length=20,
                        verbose_name="设施类型",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entrance", "入口区"),
                            ("family", "亲子区"),
                            ("thrill", "刺激区"),
                            ("view", "观光区"),
                            ("rest", "休闲区"),
                            ("catering", "餐饮配套区"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="所属区域",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "服务设施",
                "verbose_name_plural": "服务设施",
                "ordering": ["region", "name"],
            },
        ),
        migrations.AddField(
            model_name="forecastevaluation",
            name="parameters",
            field=models.JSONField(blank=True, default=dict, verbose_name="参数"),
        ),
        migrations.AddField(
            model_name="forecastevaluation",
            name="validation_end",
            field=models.DateField(blank=True, null=True, verbose_name="验证结束"),
        ),
        migrations.AddField(
            model_name="forecastevaluation",
            name="validation_start",
            field=models.DateField(blank=True, null=True, verbose_name="验证开始"),
        ),
        migrations.AddField(
            model_name="projectforecast",
            name="confidence",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="置信说明"
            ),
        ),
        migrations.AddField(
            model_name="projectforecast",
            name="is_peak_alert",
            field=models.BooleanField(default=False, verbose_name="是否高峰预警"),
        ),
        migrations.AddField(
            model_name="projectheatsnapshot",
            name="granularity",
            field=models.CharField(
                default="day", max_length=20, verbose_name="时间粒度"
            ),
        ),
        migrations.AddField(
            model_name="projectincident",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_project_incidents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="处理人",
            ),
        ),
        migrations.AddField(
            model_name="projectincident",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="project_incidents/",
                verbose_name="图片",
            ),
        ),
        migrations.AddField(
            model_name="projectincident",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="备注"),
        ),
        migrations.AddField(
            model_name="projectincident",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "待处理"),
                    ("processing", "处理中"),
                    ("resolved", "已处理"),
                ],
                default="open",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddField(
            model_name="projectreview",
            name="experience_score",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="体验评分"),
        ),
        migrations.AddField(
            model_name="projectreview",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="project_reviews/", verbose_name="图片"
            ),
        ),
        migrations.AddField(
            model_name="projectreview",
            name="queue_reasonableness_score",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="排队合理性"
            ),
        ),
        migrations.AddField(
            model_name="projectreview",
            name="safety_score",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="安全评分"),
        ),
        migrations.AlterField(
            model_name="projectreview",
            name="rating",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="评分"),
        ),
        migrations.CreateModel(
            name="MaintenanceWorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("done", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="开始时间")),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="maintenance_work_orders/",
                        verbose_name="图片",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="analytics.projectincident",
                        verbose_name="关联事件",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_work_orders",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "维护工单",
                "verbose_name_plural": "维护工单",
                "ordering": ["-started_at"],
            },
        ),
    ]
